### ISSUE TITLE
Wrong unit in Eve

### ISSUE THREAD

**Issue by jr7216** [grzegorz914/homebridge-enphase-envoy#10]
The unit of measured power is kW, but the value is W.

**Comment by jr7216** [comment]
Is it also posible to display the total power? All the inverters added up, and other details like precious versions? 
![ECFE758F-8564-4E62-AEFD-4AC889CA33AC](https://user-images.githubusercontent.com/78318050/106892827-ee399c00-66ec-11eb-91e4-d3d38d2c27ba.png)

**Comment by grzegorz914** [comment]
Please post the data of Your PV what U have installed:
Envoy type, Q-Relay, Microinverters type, Meter.
The kW unit is correct.
The Power is the TotalPower.

**Comment by jr7216** [comment]
Envoy-S-Metered-EU,IQ7+no Q-relay, no meters
For the wrong unit see the screen dump in the next post. One panel producing 22 kW?
Now installed the last version from 1 view minutes ago 4.2.13. (the first screen in Eve is a complete  mesh, see next post screendump).
I cannot find the total power in the latest version. The previous screendump is of a older version.

**Comment by jr7216** [comment]
![AF07337C-B200-4601-A20D-43082F3A0383](https://user-images.githubusercontent.com/78318050/106909313-75dcd600-6700-11eb-8e66-2e93b1defa65.jpeg)
![Uploading 743EEC73-1D92-44A2-9DFB-3DD46F87EA4B.jpeg…]()

**Comment by jr7216** [comment]
![Uploading D577F30D-3331-4970-AD91-1C8D817C5E52.png…]()

**Comment by jr7216** [comment]
![6401F963-0E4E-4717-82D1-D48156BB17CD](https://user-images.githubusercontent.com/78318050/106909474-a15fc080-6700-11eb-8077-9e0a1141c4ae.png)

**Comment by jr7216** [comment]
![Uploading 4CE724A4-66CD-4FB7-B139-8B171F73E065.png…]()

**Comment by jr7216** [comment]
![Uploading BB795ABB-734B-4A14-9665-10DE0112FE16.png…]()

**Comment by grzegorz914** [comment]
Please get The output:
http://envoy.local/inventory.json
http://envoy.local/production.json
http://envoy.local/api/v1/production

**Comment by jr7216** [comment]
[inventory.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/5926682/inventory.txt)
[production.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/5926685/production.txt)
[production-api.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/5926686/production-api.txt)

**Comment by grzegorz914** [comment]
Please get also
http://envoy.local/ivp/meters

**Comment by grzegorz914** [comment]
try update and get the feedback

**Comment by jr7216** [comment]
[meters.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/5930937/meters.txt)

The last update 4.2.28 is great again, the right units en layout (position of de information). Thnx for the effort.
