### ISSUE TITLE
Total Energy Produced Contact sensor??

### ISSUE THREAD

**Issue by ipathi1** [grzegorz914/homebridge-enphase-envoy#100]
Hey! Loved your work with this plug-in. Is it possible to code a Total Power Produced contact sensor? If I set a value and it triggers, I can automate another device (whether there was enough sunlight to heat my Solar Water heater and accordingly turn on my geyser if there wasn’t enough sunlight). A daily value reset option would be great with this. Thank you.

**Comment by grzegorz914** [comment]
Total Power Produced or Max Power Produced? I don’t quite understand what is total power produced?
Max Power Produced sensor is already there.

**Comment by ipathi1** [comment]
Correct me if I'm wrong, but Power Peak Detected is the one circled in Blue in my screenshot right? 

If so, I want value for power Produced for that day.(Circled in white)

![WhatsApp Image 2023-08-25 at 13 11 36](https://github.com/grzegorz914/homebridge-enphase-envoy/assets/143114391/b00c11ed-8f67-40db-b8bd-0b4c3d937ae9)

**Comment by grzegorz914** [comment]
Yes, Peak power is the value in blue circle, in white is energy production total at this time

**Comment by ipathi1** [comment]
Apologies, my bad.
Total Energy Produced for the day is what I am looking for.

**Comment by grzegorz914** [comment]
I will add this possibility today

**Comment by ipathi1** [comment]
Oh wow. Thank you for your time.

**Comment by grzegorz914** [comment]
Done in 7.4.0, please test and let me know.
