### ISSUE TITLE
MQTT connect error

### ISSUE THREAD

**Issue by xorguy** [grzegorz914/homebridge-enphase-envoy#104]
Hi.

Using latest update 7.4.5 does not connect to MQTT, homebridge console shows: 

[homebridge-enphase-envoy] Device: 10.1.2.3 Envoy-S, MQTT Connect error: TypeError: this.subscribe is not a function

And it does not publish any information via MQTT.
Tried with 7.4.4 and it works flawlessly,

**Comment by ahnungsbefreit** [comment]
I have the same issue,  after downgrading to previous version it worked again
