### ISSUE TITLE
Detect grid status

### ISSUE THREAD

**Issue by eleventhaus** [grzegorz914/homebridge-enphase-envoy#105]
Is there a way to detect when the system goes off grid or when the power from the grid stops?

It would be handy to be able to run an automation if the power from the grid goes out.

**Comment by grzegorz914** [comment]
We can detect enpower states: no grid, open, and closed. If this is this what you need then it can be added as a sensor.

**Comment by grzegorz914** [comment]
@eleventhaus 
in this case I need for you 2 debug logs, one if your device is ON Grid andond one if is OFF Grid, to enable debug please go to plugin settings>>advanced settings>>system>>debug enable it. Restart and get the whole log.

**Comment by grzegorz914** [comment]
I have pushed 7.5.0-beta
- added *Enpower Grid State* contact sensor for monitoring,
- added *Encharge Grid State* contact sensor for monitoring,
- added *Solar Grid State* contact sensor for monitoring

all configured in plugin settings Advanced Settings>>Ensemble section

please test and let me know

**Comment by eleventhaus** [comment]
Looking good! Thank you

**Comment by grzegorz914** [comment]
Please provide the debug log too.

**Comment by grzegorz914** [comment]
continue please in #106

**Comment by eleventhaus** [comment]
> We can detect enpower states: no grid, open, and closed

Will the enpower state show "off grid" (meaning power grid from the city is down)? or will it only show open/closed?

**Comment by grzegorz914** [comment]
@eleventhaus i don’t know because I don’t have Ensemble/Enpower, if You send me the debug log during this mode then I can check it.

**Comment by grzegorz914** [comment]
@eleventhaus read this: https://support.enphase.com/s/article/when-will-my-enphase-energy-system-go-off-grid then put your system in Grid-Off and send me the debug log.

**Comment by grzegorz914** [comment]
@eleventhaus  added in 7.11.0
