### ISSUE TITLE
Add Battery percentage as light sensor in HomeKit

### ISSUE THREAD

**Issue by AndreasBrack** [grzegorz914/homebridge-enphase-envoy#118]
First: Thank you very much for this very good tool.

You are already reading the current battery percentage from the envoy (seen in the logs), but as far as I see this is currently not available in the Apple-Homekit representation. 

Would it be possible to add that? If it is already available in HomeKit then this Issue can be treated as a documentation request.

Regards, Andreas

**Comment by grzegorz914** [comment]
I will add this in next release.

**Comment by grzegorz914** [comment]
try 7.9.0-beta.0 and let me know, the lightbulb should appear automatically where Tile ON = Batteries/Encharges `Charged level > 0`, Charged Level displayed as a slider in `%`

**Comment by AndreasBrack** [comment]
Sorry, I can’t see such a tag or a branch where you added it. 

Since I am not used to work with GitHub or manually updating the homebridge plugins I am unsure if I searched correctly. Would you please provide a link to the beta?

**Comment by grzegorz914** [comment]
npm install g home ridge-enphase-envoy@7.9.0-beta.0

**Comment by AndreasBrack** [comment]
![IMG_2755](https://github.com/grzegorz914/homebridge-enphase-envoy/assets/1390833/ac4a0b25-72f2-4aeb-b64f-9de5bb93c287)

works perfectly!

thank you very much!
