### ISSUE TITLE
Accessories

### ISSUE THREAD

**Issue by Shaun-C2** [grzegorz914/homebridge-enphase-envoy#120]
Good morning I have Envoy accessories in Home bridge.
I have the envoy child bridge installed in HomeKit. It shows no accessories .
I have tried to manually add the accessories but to no avail.
I have tried rebooting , loading and unloading everything.

very frustrating. Any ideas?

**Comment by grzegorz914** [comment]
Are You try this https://github.com/grzegorz914/homebridge-enphase-envoy/wiki#troubleshooting
