### ISSUE TITLE
Requesting grid profile error: AxiosError: Request failed with status code 401. Trying again in 15s.

### ISSUE THREAD

**Issue by rrebel01** [grzegorz914/homebridge-enphase-envoy#130]
After version update getting error: Requesting grid profile error: AxiosError: Request failed with status code 401. Trying again in 15s.

Tried reverting but no luck.

**Comment by rrebel01** [comment]
upgrading to v7.11.11 or above wil give this issues.. below still works

**Comment by grzegorz914** [comment]
debug please

**Comment by grzegorz914** [comment]
401 is authorization error

**Comment by rrebel01** [comment]
It started after upgrade to latest version.  ive tried every version error is fixed after downgrading to v7.11.10

**Comment by grzegorz914** [comment]
I don’t know what happened in your system, please post the debug log.

**Comment by cyberb0b** [comment]
Same issue here now. I received a firmware update last night (after I called with Enphase and told me my grid profile was gone) . First local certificate error. I have entered Username passs, serial and v7 firmware (Received fw D7.3.88). Now "Device: 10.10.1.248 Solar, Requesting grid profile error: AxiosError: Request failed with status code 401. Trying again in 15s."
[debug.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/14651236/debug.txt)

**Comment by grzegorz914** [comment]
Should be fixed, let me know.

**Comment by grzegorz914** [comment]
try again update

**Comment by cyberb0b** [comment]
So far it looks okay now! Much Appriciated. Especially with those new sensors! Time for me to put a relais between my washmahine and dishwasher door sensor :)
