### ISSUE TITLE
Please adhere to semver

### ISSUE THREAD

**Issue by chrisjshull** [grzegorz914/homebridge-enphase-envoy#133]
Release notes say:
```
# After update to v7.11.0 and above from plevious version the grid mode sensors need to be configured again!!!
# After update to v7.8.0 and above from plevious version the sensors need to be configured again!!!
# After update to v7.5.0 and above from plevious version the sensors need to be configured again❕❕!
```

however, semver would ask that backwards-incompatible changes be marked by new major versions.

**Comment by grzegorz914** [comment]
All this versions are compatible with previous, just added some new features and need to be configured again in some sections.

**Comment by chrisjshull** [comment]
The whole point of semver is that I shouldn't have to reconfigure anything if I don't pull in a major version - I should only be getting bug fixes and new features. But otherwise my setup should remain compatible. https://semver.org

> MAJOR version when you make incompatible API changes

The API you provide us (which we super appreciate, btw) to use homebridge-enphase-envoy *is* the config.

I just spent the last day trying to figure out why homebridge envoy wasn't working after updating homebridge and several plugins. Turns out the change from milliseconds to seconds in the config was the issue. That change should have been a major semver update.

**Comment by grzegorz914** [comment]
Why you not read changelog before update, this will save your time?
![IMG_1507](https://github.com/grzegorz914/homebridge-enphase-envoy/assets/28867813/4c83a733-3024-47fe-a67c-45428b3e1ea6)

**Comment by chrisjshull** [comment]
> Why you not read changelog before update, this will save your time?

We shouldn't have to though? Not reading the changelog for a server-minor change is zero time (and that's how I get to treat my other homebridge plugins). You can't beat zero ;)

But look - I acknowledge that at the end of the day, it's your project and you can run it how you want. I very much appreciate that it exists and will keep using it. This is just some feedback for something I think would be useful, and I'll leave it at that.
