### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tonal1ty** [grzegorz914/homebridge-enphase-envoy#136]
![IMG_3007](https://github.com/grzegorz914/homebridge-enphase-envoy/assets/150700152/8a514096-bc20-4296-a5d4-8472a187f708)

**Comment by grzegorz914** [comment]
Please post whole debug log

**Comment by Tonal1ty** [comment]
[homebridge.log(1).txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/15505162/homebridge.log.1.txt)

**Comment by grzegorz914** [comment]
try 7.14.8-beta.2 and get the debug, debug need to be enabled in plugin config, advanced section >>> system

**Comment by grzegorz914** [comment]
@Tonal1ty 
still the error in latest release
