### ISSUE TITLE
Info cpl

### ISSUE THREAD

**Issue by Tonal1ty** [grzegorz914/homebridge-enphase-envoy#137]
Hello, can the plugin cause CPL problems? with the fast refresh rate?

**Comment by grzegorz914** [comment]
What you mean CPL? please be more specific.

**Comment by Tonal1ty** [comment]
Envoy s communicates with the microinverters by cpl. I wonder if asking for constant information does not saturate the CPL line. cpl = PLC .

**Comment by grzegorz914** [comment]
PLC communications have nothing to do with local api, so both can working without interference.
