### ISSUE TITLE
Missing sensor in HomeKit app, but als not visible on accessoires overview page in Homebridge

### ISSUE THREAD

**Issue by eronnes** [grzegorz914/homebridge-enphase-envoy#138]
I've got te script working, in the Homebridgelog I see data which comes from my solar installation. But I don't see any sensor-information in my Homekit app. What do I wrong?

Could you please advise, thank you.

**Comment by grzegorz914** [comment]
Aere you ad the accessory to the home app?

**Comment by eronnes** [comment]
Yes, and a lot of assessories were visible, except for the Enphase plugin assessories.

**Comment by grzegorz914** [comment]
Please read this: https://github.com/grzegorz914/homebridge-enphase-envoy?tab=readme-ov-file#about-the-plugin

**Comment by eronnes** [comment]
I did, but looks like I did everything as stated. Should I see the Accessoires (sensors) in Accessoires overview in Homebridge itself?

**Comment by grzegorz914** [comment]
yes, the sensors are visible in homebridge and in home app, if you have some problems please post the debug log then I can look what is going wrong. To enable debug mode go to plugin settings advanced section>>>system>>debug

**Comment by eronnes** [comment]
I found this issue in the logging:
[20-6-2024, 09:11:39] [homebridge-enphase-envoy] Device: xxx.xxx.xxx.xxx Envoy-S, Start error: Requesting power production mode error: AxiosError: Request failed with status code 401., trying again in 15s.

Replaced ip with xxx.xxx.xxx.xxx

**Comment by eronnes** [comment]
I've turned of supportProductionPowerMode 

If enabled, control Production Power Mode will be possible in Envoy section (EVE or Controler app), Fw. 7.x.x and newer required installer credentials data.

Now I see sensors coming up!

**Comment by grzegorz914** [comment]
Yes, to read/write Production Power Mode and PLC level, Installer credentials data are required in other things wil return error 401 - wrong credentials data.

I think is solved now.
