### ISSUE TITLE
Trouble using with HOOBS

### ISSUE THREAD

**Issue by logal727** [grzegorz914/homebridge-enphase-envoy#141]
Hi there,

Is there a trick to get this to work with HOOBS, I see it's HOOBS certified, and Ive done all sorts of changes to the config file, but it seems like under HOOBS it does not recognize the changes I put there. I keep getting the "self signed certificate" login error, which I've generated the token and tried to use that as well and also just using Enlighten UN and PW config options. 

The `envoyToken` and enlighten username and password config options don't seem to do anything even though I fill them out. Anyone had success lately with HOOBS and this? Thanks!

**Comment by grzegorz914** [comment]
Please post the debug log (go to plugin settings>>advanced settings>>system>>debug), plugin version, envoy version firmware and the config.

**Comment by logal727** [comment]
Actually, I got it working! The documentation with the GitHub and the HOOBS listing is different, HOOBS listing may need updating at some point  On Jul 22, 2024, at 11:55 PM, Grzegorz ***@***.***> wrote:﻿
Please post the debug log (go to plugin settings>>advanced settings>>system>>debug), plugin version, envoy version firmware and the config.
