### ISSUE TITLE
Is there a way to detect if the local city grid is down?

### ISSUE THREAD

**Issue by eleventhaus** [grzegorz914/homebridge-enphase-envoy#142]
On the enphase web portal and on the enphase app, there is a indicator for the local municipal grid.

![Screenshot 2024-07-25 at 10 01 53 AM](https://github.com/user-attachments/assets/bd866c90-7366-4e3a-9465-d43e1e306a0d)

Is there a way to expose this indicator in the plugin as a sensor which reflects the status of the municipal grid?

A sensor would make it easy to create shortcuts using homekit in iOS, where a certain set of actions could be run if the local grid goes down.

**Comment by grzegorz914** [comment]
Yes, the sensor can be created in Enpower or Solar section
![IMG_0996](https://github.com/user-attachments/assets/045648a6-2133-417c-9f18-156958dafbce)

**Comment by eleventhaus** [comment]
I have the following sensors created in the plugin config: Enpower Grid On, Enpower Grid Off, Enpower Multimode On, Enpower Multimode Off


https://github.com/user-attachments/assets/9d50d8fb-ceab-4a0c-a222-22c388af82fb

This is what my homekit looks like:
![self-consumption_Screenshot 2024-07-26 at 10 00 37 AM](https://github.com/user-attachments/assets/d1040a53-c39f-4c94-85da-975c02cf4123)

This is what my enphase portal looks like:
![Screenshot 2024-07-26 at 10 06 37 AM](https://github.com/user-attachments/assets/d43e456f-a574-488b-a5f6-9704ea3e9c7b)

If I have Enpower Grid On active as a sensor in the plugin config, why is it off in Homekit?

Will the Grid On sensor not work with my system because I have solar and storage? Should I only use multimode grid then?

**Comment by grzegorz914** [comment]
Yes, You need use multimode-grid on or off sensor for Your purpose.

**Comment by eleventhaus** [comment]
Thought everything was working well but this morning I noted that although my system is on the grid and everthing is working as expected, all of the sensors I created in homekit using the plugin are reading as closed or off

![Screenshot 2024-07-27 at 9 57 34 AM](https://github.com/user-attachments/assets/e384ee86-41b9-4923-80f6-cb45e690dbdf)

![Screenshot 2024-07-27 at 9 58 07 AM](https://github.com/user-attachments/assets/777cc857-356c-4e53-bae9-131cdb5f29ef)

These are all enpower sensors
![Screenshot 2024-07-27 at 10 00 17 AM](https://github.com/user-attachments/assets/282fbad4-fb00-445e-b572-9a26840164c7)

**Comment by grzegorz914** [comment]
Can you get me debug log, go to plugin settings advanced settings>>system>>debug enable it and restart plugin then after a while download and post the log file.

**Comment by eleventhaus** [comment]
[homebridge-enphase-envoy.log.txt](https://github.com/user-attachments/files/16433749/homebridge-enphase-envoy.log.txt)

**Comment by grzegorz914** [comment]
Should be fixed in 8.0.2, try and let me know

**Comment by grzegorz914** [comment]
You can also try beta 9.0.0, here is added support for Homebridge 2.0 and new sensor profiles to select , `Grid Tied`and `Grid Forming`

**Comment by eleventhaus** [comment]
Just to confirm:

- grid tied means municipal grid is working
- grid forming mean municipal grid is down

**Comment by grzegorz914** [comment]
in release v8.1.1 fixed display and publish ensemble status.
Also fixed  encharge and solar grid mode sensors, please update and get me the debug please

**Comment by eleventhaus** [comment]
Updated to 8.1.1

[homebridge-enphase-envoy.log (2).txt](https://github.com/user-attachments/files/16488312/homebridge-enphase-envoy.log.2.txt)

**Comment by grzegorz914** [comment]
Encharge profile are in experimental phase and not working yet, please disable it in plugin config Ensemble>>Encharge>>Profile

**Comment by eleventhaus** [comment]
I'm not sure the Grid Tied/Forming or Multimode sensors can be used to indicate if the utility is online or offline.

In my case, Grid Tied shows as off/Multimode shows as on when my system starts using battery power regardless of utility grid status. When utility grid is off none of the indicators reflect that.

I need a sensor that will indicate when the ultility is down. Is that possible?

**Comment by grzegorz914** [comment]
I Don’t have ensemble in my system, Please post debug log if grid is off,  albo if grid is on

**Comment by grzegorz914** [comment]
HI @eleventhaus  in latest 9.0 beta im added empower grid state sensor which represent Grid ON/OFF state, please try it and let mi know.

**Comment by eleventhaus** [comment]
I updated to the latest beta and I'm getting the following error:
"Device: 192.168.107.60 Envoy, Start error: Requesting ensemble inventory error: ReferenceError: enpwrGridMode is not defined., trying again in 15s."

[homebridge-enphase-envoy.log (3).txt](https://github.com/user-attachments/files/16552171/homebridge-enphase-envoy.log.3.txt)

**Comment by grzegorz914** [comment]
fixed, beta 132 added also Enpower Grid State control enable it in enpower section

**Comment by eleventhaus** [comment]
Fixed the last error.

New error: "Device: 192.168.107.60 Envoy, Start error: Requesting ensemble status error: TypeError: parseFloat is not a function., trying again in 15s."

[homebridge-enphase-envoy.log (4).txt](https://github.com/user-attachments/files/16552450/homebridge-enphase-envoy.log.4.txt)

**Comment by grzegorz914** [comment]
try 134

**Comment by eleventhaus** [comment]
I'm on 135. I added the Grid State Control as a switch and Grid State Sensor as a contact sensor but not seeing them on homekit

![Screenshot 2024-08-08 at 12 32 46 PM](https://github.com/user-attachments/assets/1f4e42e9-31c9-446b-ad92-a7e0e5cbe42d)

![Screenshot 2024-08-08 at 12 25 50 PM](https://github.com/user-attachments/assets/f350e20d-80dc-4b33-a8bc-f6518452c745)

![Screenshot 2024-08-08 at 12 25 56 PM](https://github.com/user-attachments/assets/146dd9d3-556a-4663-9b65-eb19ef821728)

[homebridge-enphase-envoy.log (6).txt](https://github.com/user-attachments/files/16552616/homebridge-enphase-envoy.log.6.txt)

**Comment by grzegorz914** [comment]
136 fixed

**Comment by eleventhaus** [comment]
On 141

Still not seeing the Grid State Control or Grid State Sensor in homekit

Also, getting these non-critical errors on homebridge:

```
[08/08/2024, 16:07:01] [homebridge-enphase-envoy] This plugin generated a warning from the characteristic 'Rest power': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[08/08/2024, 16:07:15] [homebridge-enphase-envoy] This plugin generated a warning from the characteristic 'Rest power': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[08/08/2024, 16:07:30] [homebridge-enphase-envoy] This plugin generated a warning from the characteristic 'Rest power': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[08/08/2024, 16:07:45] [homebridge-enphase-envoy] This plugin generated a warning from the characteristic 'Rest power': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[08/08/2024, 16:08:00] [homebridge-enphase-envoy] This plugin generated a warning from the characteristic 'Rest power': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[08/08/2024, 16:08:15] [homebridge-enphase-envoy] This plugin generated a warning from the characteristic 'Rest power': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[08/08/2024, 16:08:30] [homebridge-enphase-envoy] This plugin generated a warning from the characteristic 'Rest power': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[08/08/2024, 16:08:45] [homebridge-enphase-envoy] This plugin generated a warning from the characteristic 'Rest power': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[08/08/2024, 16:09:00] [homebridge-enphase-envoy] This plugin generated a warning from the characteristic 'Rest power': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[08/08/2024, 16:09:15] [homebridge-enphase-envoy] This plugin generated a warning from the characteristic 'Rest power': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
```

[homebridge-enphase-envoy.log (7).txt](https://github.com/user-attachments/files/16554098/homebridge-enphase-envoy.log.7.txt)

**Comment by grzegorz914** [comment]
thanks for your patience, the control grid is fixed in 142, please test it and let me know with log

**Comment by grzegorz914** [comment]
please post in this topic #144

**Comment by eleventhaus** [comment]
Geting error:

```
[10/08/2024, 09:23:14] [homebridge-enphase-envoy] Device: 192.168.107.60 Envoy, Start error: Requesting ensemble status error: TypeError: Cannot set properties of undefined (setting 'status')., trying again in 15s.
```

[homebridge-enphase-envoy.log (8).txt](https://github.com/user-attachments/files/16570259/homebridge-enphase-envoy.log.8.txt)

**Comment by grzegorz914** [comment]
ok, try 196

**Comment by eleventhaus** [comment]
v202

`[10/08/2024, 18:28:45] [homebridge-enphase-envoy] Device: 192.168.107.60 Envoy, Start error: Requesting ensemble dry contacts error: AxiosError: Request failed with status code 404., trying again in 15s.`

[homebridge-enphase-envoy.log (9).txt](https://github.com/user-attachments/files/16571284/homebridge-enphase-envoy.log.9.txt)

**Comment by grzegorz914** [comment]
203 fixes the wrong url to dry contacts

**Comment by eleventhaus** [comment]
On 203

`[10/08/2024, 22:20:58] [homebridge-enphase-envoy] Device: 192.168.107.60 Envoy, Start error: Requesting ensemble dry contacts error: AxiosError: Request failed with status code 404., trying again in 15s.`

[homebridge-enphase-envoy.log (10).txt](https://github.com/user-attachments/files/16571651/homebridge-enphase-envoy.log.10.txt)

**Comment by grzegorz914** [comment]
fixed in 204

**Comment by eleventhaus** [comment]
`[10/08/2024, 22:41:16] [homebridge-enphase-envoy] Device: 192.168.107.60 Envoy, Start error: Prepare accessory error: Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: 00000254-000B-1000-8000-0026BB765291, trying again in 15s.`

[homebridge-enphase-envoy.log (11).txt](https://github.com/user-attachments/files/16571683/homebridge-enphase-envoy.log.11.txt)

**Comment by grzegorz914** [comment]
fixed in 205

**Comment by grzegorz914** [comment]
plese post debug also if working correct

**Comment by eleventhaus** [comment]
On 206

Homekit sensors are finally working and showing correct status.

Getting the following error:
`[10/08/2024, 23:29:34] [homebridge-enphase-envoy] Device: 192.168.107.60 Envoy, Update ensemble error: Requesting ensemble encharge settings. error: TypeError: Cannot read properties of undefined (reading 'mode')..`

[homebridge-enphase-envoy.log (13).txt](https://github.com/user-attachments/files/16571820/homebridge-enphase-envoy.log.13.txt)

**Comment by grzegorz914** [comment]
208 ready

**Comment by eleventhaus** [comment]
v 241

`[11/08/2024, 08:02:57] [homebridge-enphase-envoy] Device: 192.168.107.60 Envoy, Start error: Requesting ensemble status error: TypeError: Cannot read properties of undefined (reading 'forEach')., trying again in 15s.`

[homebridge-enphase-envoy.log (14).txt](https://github.com/user-attachments/files/16574099/homebridge-enphase-envoy.log.14.txt)

**Comment by grzegorz914** [comment]
Fixed in 243

**Comment by eleventhaus** [comment]
243

`[11/08/2024, 08:12:14] [homebridge-enphase-envoy] Device: 192.168.107.60 Envoy, Start error: Requesting ensemble status error: TypeError: Cannot read properties of undefined (reading 'gridProfile')., trying again in 15s.`

[homebridge-enphase-envoy.log (15).txt](https://github.com/user-attachments/files/16574122/homebridge-enphase-envoy.log.15.txt)

**Comment by grzegorz914** [comment]
Fixed 245

**Comment by eleventhaus** [comment]
`[11/08/2024, 08:24:07] [homebridge-enphase-envoy] Device: 192.168.107.60 Envoy, Start error: Requesting dry contacts error: ReferenceError: date is not defined., trying again in 15s.`

[homebridge-enphase-envoy.log (16).txt](https://github.com/user-attachments/files/16574158/homebridge-enphase-envoy.log.16.txt)

**Comment by grzegorz914** [comment]
Fixed 247

**Comment by eleventhaus** [comment]
`[11/08/2024, 08:47:38] [homebridge-enphase-envoy] Device: 192.168.107.60 Envoy, Start error: Prepare accessory error: TypeError: Cannot read properties of undefined (reading 'type'), trying again in 15s.`

[homebridge-enphase-envoy.log (17).txt](https://github.com/user-attachments/files/16574212/homebridge-enphase-envoy.log.17.txt)

**Comment by grzegorz914** [comment]
Fixed 248

**Comment by eleventhaus** [comment]
No critical errors and homekit is working ✅😌

Thank you!

[homebridge-enphase-envoy.log (18).txt](https://github.com/user-attachments/files/16574225/homebridge-enphase-envoy.log.18.txt)

**Comment by grzegorz914** [comment]
i have fixed some warnings, try 251 and post the log please

**Comment by eleventhaus** [comment]
270

`[11/08/2024, 17:39:10] [homebridge-enphase-envoy] Device: 192.168.107.60 Envoy, Start error: Requesting ensemble status error: TypeError: Cannot set properties of undefined (setting 'status')., trying again in 15s.`

[homebridge-enphase-envoy.log (19).txt](https://github.com/user-attachments/files/16576583/homebridge-enphase-envoy.log.19.txt)

**Comment by grzegorz914** [comment]
fixed 271

**Comment by eleventhaus** [comment]
289

`[12/08/2024, 08:35:10] [homebridge-enphase-envoy] Device: 192.168.107.60 Envoy, Start error: Requesting tariff. error: TypeError: Cannot read properties of undefined (reading 'code')., trying again in 15s.`

[homebridge-enphase-envoy.log (20).txt](https://github.com/user-attachments/files/16589010/homebridge-enphase-envoy.log.20.txt)

**Comment by grzegorz914** [comment]
Fixed typo 290 ready

**Comment by eleventhaus** [comment]
Not seeing 290 on the version list for the plugin

**Comment by grzegorz914** [comment]
Try now

**Comment by eleventhaus** [comment]
292

Homekit is working, no critical errors

[homebridge-enphase-envoy.log (21).txt](https://github.com/user-attachments/files/16589531/homebridge-enphase-envoy.log.21.txt)

**Comment by grzegorz914** [comment]
293 fixed rest power characteristics warning

**Comment by grzegorz914** [comment]
294 should fixed ConfiguredName warning,

I think all errors are fixed now, please try call functions regarding uncharges empowers, I don't have it in my environment.

**Comment by eleventhaus** [comment]
294

No warning or errors. Homekit working.

[homebridge-enphase-envoy.log (22).txt](https://github.com/user-attachments/files/16589758/homebridge-enphase-envoy.log.22.txt)

**Comment by eleventhaus** [comment]
>please try call functions regarding uncharges empowers

Not sure what this means. What are call functions? Encharges or Enpower? Or both?

**Comment by grzegorz914** [comment]
for example for encharge You can change Profile, for empower set Grid ON/OFF, all functions can be created in plugin config menu

**Comment by grzegorz914** [comment]
you can also control Dry Contacts

**Comment by eleventhaus** [comment]
296

`[12/08/2024, 11:03:26] [homebridge-enphase-envoy] Device: 192.168.107.60 Envoy, Start error: Prepare accessory error: TypeError: this.pv.envoy.home.wirelessConnektions is not iterable, trying again in 15s.`

[Uploading homebridge-enphase-envoy.log (23).txt…]()

**Comment by grzegorz914** [comment]
fixed

**Comment by eleventhaus** [comment]
[homebridge-enphase-envoy.log (24).txt](https://github.com/user-attachments/files/16590854/homebridge-enphase-envoy.log.24.txt)

**Comment by eleventhaus** [comment]
314

`[12/08/2024, 16:44:41] [homebridge-enphase-envoy] Device: 192.168.107.60 Envoy, Start error: Requesting ensemble inventory error: TypeError: encharges.forEach is not a function., trying again in 15s.`

[homebridge-enphase-envoy.log (25).txt](https://github.com/user-attachments/files/16592767/homebridge-enphase-envoy.log.25.txt)

**Comment by eleventhaus** [comment]
Homekit working now. No critical errors.

[homebridge-enphase-envoy.log (26).txt](https://github.com/user-attachments/files/16605160/homebridge-enphase-envoy.log.26.txt)

**Comment by grzegorz914** [comment]
As info, your refresh time for liberała and meters is set in config  to very long time, Please go to Advanced Settings>>>System>>>Refresh Time and set correct values.

**Comment by eleventhaus** [comment]
What are the correct values?

**Comment by grzegorz914** [comment]
Just use the sliders to set correct value

**Comment by eleventhaus** [comment]
My cities utility grid went down today but the Grid State Sensor never closes or indicates that the utility is off

![Screenshot 2024-09-08 at 5 08 50 PM](https://github.com/user-attachments/assets/68875ed5-6afe-4b15-bdab-ab1d24138117)

[homebridge-enphase-envoy.log (1).txt](https://github.com/user-attachments/files/16924114/homebridge-enphase-envoy.log.1.txt)

**Comment by grzegorz914** [comment]
Please enable debug mode in plugin settings Advanced Settings >> System>> Log>>Debug, enable it and post the log. I see some warning in your device, I want to check from where is it.

**Comment by eleventhaus** [comment]
[homebridge-enphase-envoy.log (2).txt](https://github.com/user-attachments/files/16949034/homebridge-enphase-envoy.log.2.txt)

**Comment by grzegorz914** [comment]
9.3.7-beta.3 addressed grid state sensor, try and let me know.

**Comment by grzegorz914** [comment]
Many thanks, it will be very helpful if You post the debug log few minutes after grid went down.

**Comment by eleventhaus** [comment]
The grid in my neighborhood just went down. The system worked as expect and switched to battery consumption but I'm still unable to set up the plugin to detect when the grid is down via homekit.

Here is my my [homebridge-enphase-envoy.log.txt](https://github.com/user-attachments/files/18805241/homebridge-enphase-envoy.log.txt)

Hope it helps. Let me know if you need anything else

**Comment by grzegorz914** [comment]
You need to enable debug mode in plugin config and get the log if the grid is down and up.

**Comment by eleventhaus** [comment]
Here's the debug log. The grid went offline around 7:50 (± 5 min) and came back online around 9am (± 5 min)

[homebridge-enphase-envoy.log-2.txt](https://github.com/user-attachments/files/18829571/homebridge-enphase-envoy.log-2.txt)

**Comment by grzegorz914** [comment]
The log contain only error
