### ISSUE TITLE
Warning about 'Grid profile' with latest 9.0.3 and requirement for homebridge v2.0

### ISSUE THREAD

**Issue by xorguy** [grzegorz914/homebridge-enphase-envoy#146]
Hi.

With latest 9.0.3 version and HB 1.8.4, after reconfiguring MQTT and REST, a warning appears:

`[homebridge-enphase-envoy] This plugin generated a warning from the characteristic 'Grid profile': characteristic value expected string and received undefined. See https://homebridge.io/w/JtMGR for more info.`
It is repeated few times every some time.

When starting the plugin it complains about requiring version 2.0 or greater, but latest official still is 1.8.4, although the plugin seems to be working, except for the warning from above.

**Comment by grzegorz914** [comment]
Can you post debug?
