### ISSUE TITLE
Error: Requesting production ct error

### ISSUE THREAD

**Issue by eleventhaus** [grzegorz914/homebridge-enphase-envoy#152]
`[27/08/2024, 08:16:30] [homebridge-enphase-envoy] Device: 192.168.107.60 Envoy, Error: Requesting production ct error: timeout of 15000ms exceeded, trying again in 20s.`

(removed logs)

**Comment by grzegorz914** [comment]
in 9.3.4 i have increased timeout to 20 sec, please reduce little refresh time for production because lead to freeze the envoy.

please post whole debug log after update, I want to check characteristic 'On': characteristic value expected boolean and received undefined.

**Comment by eleventhaus** [comment]
I increased refresh time to 3 seconds for meters, production, ensemble and live data just to be sure

[homebridge-enphase-envoy.log (6).txt](https://github.com/user-attachments/files/16786104/homebridge-enphase-envoy.log.6.txt)

**Comment by grzegorz914** [comment]
can you enable debug and then post the log please

**Comment by eleventhaus** [comment]
Seems to be working fine now

[homebridge-enphase-envoy.log (7).txt](https://github.com/user-attachments/files/16850829/homebridge-enphase-envoy.log.7.txt)

**Comment by 0berkampf** [comment]
Same issue here with version 9.3.6, those 2 errors are shown:
Error:  Requesting production ct error: timeout of 25000ms exceeded, trying again.
Error: Requesting inventory error: timeout of 25000ms exceeded, trying again.

**Comment by grzegorz914** [comment]
Try to power cycle your Envoy, because is not a plugin problem, I thinh. Please albo post the debug log.

**Comment by grzegorz914** [comment]
Probably You have very poor WiFi connection to your Envoy, 25sec timeout is very long.

**Comment by 0berkampf** [comment]
I’m not sure about the WIFI connection quality because those errors occur less frequently when I increase the Production Refresh Time. I’m trying with 20s for the moment and check tomorrow if errors are shown again.

**Comment by grzegorz914** [comment]
Still the issue?

**Comment by grzegorz914** [comment]
This error happened if the refresh time is too short, Envoy CPU is poor.
