### ISSUE TITLE
Recent update seems to have broker Apple Home Integratio 

### ISSUE THREAD

**Issue by CaptainPic** [grzegorz914/homebridge-enphase-envoy#153]
Suddenly seeing non-response areas for Envoy items in Apple Home and also getting errors in Homebridge on start of child bridge with recent release (9.3.4 now) suggesting Homebridge needs to be version2.0> and "Enphase, Error: Requesting inventory error: enserblesis not defined,trying again."

Will moving to HB 2.0 fix this?  I'm running other plugins so perhaps a roll back to one of the Version 8's of the Enhphase plug-in?

![IMG_1776](https://github.com/user-attachments/assets/c82d48c7-a2d1-470f-9fbb-ae883d80ec44)

[Screenshot 2024-08-31 at 3.56.44 PM.pdf](https://github.com/user-attachments/files/16825970/Screenshot.2024-08-31.at.3.56.44.PM.pdf)

[Screenshot 2024-08-31 at 3.54.44 PM.pdf](https://github.com/user-attachments/files/16825971/Screenshot.2024-08-31.at.3.54.44.PM.pdf)

**Comment by grzegorz914** [comment]
fixed in 9.3.5
