### ISSUE TITLE
Installation error - JWT token not valid

### ISSUE THREAD

**Issue by learning2code-11** [grzegorz914/homebridge-enphase-envoy#160]
Hello,

Newbie here. 
using my Synology NAS - Homebridge (Homebridge UI)

Installed the plugin "homebridge-enphase-envoy" 
Getting an error during the configuration.

I am a self installer for solar panels. so have installer credentials too.
entered all as per your recommendations. can u please help me resolve this issue.
Logs show individual panel power details but i cant see any device or details in the accessories.

Please help me to understand what i am missing here

<img width="398" alt="Screenshot 2024-09-17 at 9 48 02 PM" src="https://github.com/user-attachments/assets/9c786eac-d580-4a36-a114-0e574d700da3">

<img width="809" alt="Screenshot 2024-09-17 at 9 48 16 PM" src="https://github.com/user-attachments/assets/33468510-b52f-4c21-8baa-75356d3f065c">

Thanks

**Comment by grzegorz914** [comment]
Are you add the accessory to home app https://github.com/grzegorz914/homebridge-enphase-envoy/wiki#adding-to-homekit
