### ISSUE TITLE
Enphase Plugin Stops Updating After Night Without Restart

### ISSUE THREAD

**Issue by BenouGui** [grzegorz914/homebridge-enphase-envoy#161]
Hi,

I'm using the Enphase plugin to send data from my solar panels to MQTT. Everything works well during the day, but after a night of no solar production, the plugin stops updating, and I no longer receive any panel data. To fix this, I need to restart the plugin each morning.

Additionally, it's quite difficult to pinpoint in the logs exactly when the plugin stops updating or goes inactive. This makes troubleshooting more complicated.

Could you please look into this issue? Let me know if you need any logs or further details.

Thank you for your help!

![IMG_7129](https://github.com/user-attachments/assets/7c93757e-3d57-408f-8841-803dd7617c48)

**Comment by grzegorz914** [comment]
Try latest beta and let me know

**Comment by grzegorz914** [comment]
beta 14 will try reconnect if error occurs, please let me know tomorrow after test.

**Comment by BenouGui** [comment]
Thank you for the suggestion!

Yesterday, I installed beta 16, but unfortunately, this morning the plugin stopped updating again, and I had to reboot it to get it working. It seems the issue still persists.

I've attached the logs from this morning:

The first part shows when the plugin stopped updating.
The second part is from after I rebooted the plugin.
Let me know if there's anything else I should try or provide.

Thanks again for your help!

[homebridge.log.before.txt](https://github.com/user-attachments/files/17444447/homebridge.log.before.txt)
[homebridge.log.after.txt](https://github.com/user-attachments/files/17444448/homebridge.log.after.txt)

**Comment by grzegorz914** [comment]
Your envoy just doesn’t respond to the request, as You see the plugin trying to connect again without success. May be You set to short fats refresh time.

**Comment by BenouGui** [comment]
Thank you for the response!

I understand that the plugin is trying to connect without success, but I’m wondering why everything works perfectly after I restart the plugin, and I didn’t have this issue before. If the refresh time was too short, wouldn’t the problem persist even after restarting?

I’ll try increasing the refresh time and see if that makes a difference. Let me know if there’s anything else I should check.

Thanks again for your help!

**Comment by grzegorz914** [comment]
I testing this on my side and is working correct as of beta 16, I will investigate more time for this issue.

**Comment by BenouGui** [comment]
Just an update:

This morning, with version v9.4.1-beta.47, I didn’t need to reboot the plugin, and everything worked as expected. I’ll continue monitoring, but it looks promising so far.

Thanks again for your help!

**Comment by grzegorz914** [comment]
I think latest beta.77 solved the issue, any info from your side.?

**Comment by BenouGui** [comment]
Yes, with beta 77 everything worked fine, no issues to report. I’ve just updated to beta 78 and will check tomorrow morning to see if everything is still stable.

Thanks for following up!

**Comment by grzegorz914** [comment]
v9.4.1 released, I think is fixed finally.

**Comment by grzegorz914** [comment]
@BenouGui any info ?

**Comment by BenouGui** [comment]
Everything is working well now—no issues to report. Thanks for the support and the updates!
