### ISSUE TITLE
Error for version 9 and above

### ISSUE THREAD

**Issue by rrebel01** [grzegorz914/homebridge-enphase-envoy#163]
Iam keep getting this error if i upgrade from v8.1.1 and above:

[11/14/2024, 9:19:33 PM] [homebridge-enphase-envoy] Device: 192.168.250.53 Envoy Rebel, Error: Start error: Error: Update ensemble status error: Request failed with status code 401, trying again.

V8.1.1 seems to work fine. All versions higher are not working.

**Comment by grzegorz914** [comment]
Can you post debug log please?

**Comment by rrebel01** [comment]
what is the best way to find thedebug log?

**Comment by grzegorz914** [comment]
Go to plugin config, Advanced Settings>>>System>>>Debug enable it, save and restart, then download the log and post.

**Comment by rrebel01** [comment]
Where is the log saved?

**Comment by rrebel01** [comment]
[homebridge-enphase-envoy.log.txt](https://github.com/user-attachments/files/17791018/homebridge-enphase-envoy.log.txt)

**Comment by rrebel01** [comment]
[Uploading homebridge-enphase-envoy.log.txt…]()

**Comment by rrebel01** [comment]
[homebridge-enphase-envoy.log.txt](https://github.com/user-attachments/files/17791033/homebridge-enphase-envoy.log.txt)

**Comment by grzegorz914** [comment]
Fixed in 9.4.3

**Comment by rrebel01** [comment]
Yes it works! thanks for the fast and great service!!

**Comment by rrebel01** [comment]
Just found out that i lost my 2 sensors in Homekit. 

config is still there but sensors not visable:

     "displayType": 0
                    },
                    "powerConsumptionNetLevelSensors": [
                        {
                            "name": ">5Kw to Net",
                            "powerLevel": -5000,
                            "displayType": 0
                        },
                        {
                            "name": ">4.4Kw to Net",
                            "powerLevel": -4400,
                            "displayType": 0
                        },
                        {
                            "powerLevel": 0,
                            "displayType": 0

**Comment by rrebel01** [comment]
![IMG_3282](https://github.com/user-attachments/assets/e00b909a-9e70-40a2-87de-02f0b64a4e1d)

**Comment by grzegorz914** [comment]
You need enable it, display type `0` mean `disabled`

**Comment by rrebel01** [comment]
I re-enabled it and changed it back to contact. But my shortcuts in homekit have disappared. Those shortcuts where pretty complex. Is there a way to get them back?
