### ISSUE TITLE
Negative power level sensors are seen as positive. 

### ISSUE THREAD

**Issue by rrebel01** [grzegorz914/homebridge-enphase-envoy#164]
In older versions i had contacts to trigger my waterheater if solar production excees 4400W. 

After upgrade contact keeps trigger at consumption instead of productions. See attachments.
<img width="548" alt="Config" src="https://github.com/user-attachments/assets/f35ac35e-ab1c-43e3-b4a3-d59d41c4cf8b">
![WhatsApp Image 2024-11-17 at 8 11 23 PM (2)](https://github.com/user-attachments/assets/4f0bf4f0-ccea-4b28-86d3-39542ddd773f)
![WhatsApp Image 2024-11-17 at 8 11 23 PM](https://github.com/user-attachments/assets/19bd7c13-fe6b-4805-9385-64c5e9a2b3fb)

**Comment by grzegorz914** [comment]
In Your case you neeed to create this sensors in Production section.

**Comment by rrebel01** [comment]
I need production - consumption.

if total flow to net is greater then 4400w.

i always did this on your advise to use a negative number in the powerlevel sensor. What would be the best way now?

**Comment by grzegorz914** [comment]
You have 3 options to create sensors:
Production - always positive, PV
Consumption Total - always positive, Home
Consumption Net - positive or negative based on current power, Grid

**Comment by rrebel01** [comment]
Consumption Net is what i use, but its not handling negative numbers correctly:

![image](https://github.com/user-attachments/assets/9d178903-6597-4429-998c-59e921aae9fb)

**Comment by grzegorz914** [comment]
Can you post debug, I will look into this issue.

**Comment by grzegorz914** [comment]
Try 9.4.5-beta.0 and let me know

**Comment by rrebel01** [comment]
At this monent the contacts dont seem to react to positive nor negative values

**Comment by grzegorz914** [comment]
I have already debug this on my side and all working as expected, if doesn’t work on your side please post debug log

**Comment by rrebel01** [comment]
her you go:

![WhatsApp Image 2024-11-19 at 14 00 21_3e20711b](https://github.com/user-attachments/assets/b75c05a9-48e8-43ed-ad38-8610a33ce494)

![WhatsApp Image 2024-11-19 at 14 00 21_44c0b2c3](https://github.com/user-attachments/assets/acdada0f-1998-4a81-9322-26b057da548f)

[homebridge-enphase-envoy.log.txt](https://github.com/user-attachments/files/17819467/homebridge-enphase-envoy.log.txt)

**Comment by grzegorz914** [comment]
All correct:
Here the power:
![IMG_1037](https://github.com/user-attachments/assets/8143ee48-9071-4e85-8922-d3586ad834a7)
Here the sensors;
![IMG_1036](https://github.com/user-attachments/assets/27647654-962a-464c-a4b8-70ff0bd724d3)

**Comment by rrebel01** [comment]
Sensors have not been active in homekit all day, ive put notification on it. they have not been triggered i will delete the bridge and rejoin it in homekit, to see if that helps

**Comment by rrebel01** [comment]
ive removed the bridge from homekit and rejoined. But contacts in homekit dont change state.

**Comment by grzegorz914** [comment]
Really strange, on my side all is working correct and no any other user report problem with this

![IMG_1038](https://github.com/user-attachments/assets/2b879af0-7e54-48c2-baad-0e70306e4a38)

**Comment by rrebel01** [comment]
Ive added a positive sensor as a test and get this error now:

/homebridge/node_modules/homebridge-enphase-envoy/index.js:41
          log.warn(`Device: ${host} ${deviceName}, Name missing: ${deviceName}.`);
                              ^
ReferenceError: Cannot access 'host' before initialization
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-enphase-envoy/index.js:41:31)
    at HomebridgeAPI.emit (node:events:514:28)
    at HomebridgeAPI.signalFinished (/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/homebridge/node_modules/homebridge/src/childBridgeFork.ts:194:14)
[11/20/2024, 10:57:53 AM] [homebridge-enphase-envoy] Child bridge process ended
[11/20/2024, 10:57:53 AM] [homebridge-enphase-envoy] Process Ended. Code: 1, Signal: null

**Comment by grzegorz914** [comment]
Post your config please

**Comment by rrebel01** [comment]
{
    "devices": [
        {
            "name": "Envoy Rebel",
            "host": "192.168.250.53",
            "envoyFirmware7xx": true,
            "envoyFirmware7xxTokenGenerationMode": 0,
            "envoySerialNumber": "122033006047",
            "enlightenUser": "xxxxxl",
            "enlightenPasswd": "xxxx",
            "supportPlcLevel": false,
            "plcLevelControl": {
                "displayType": 0
            },
            "supportPowerProductionState": false,
            "powerProductionStateControl": {
                "displayType": 0
            },
            "powerProductionSummary": 11500,
            "powerProductionStateSensor": {
                "displayType": 0
            },
            "powerProductionLevelSensors": [
                {
                    "powerLevel": 0,
                    "displayType": 0
                }
            ],
            "energyProductionStateSensor": {
                "displayType": 0
            },
            "energyProductionLevelSensors": [
                {
                    "energyLevel": 0,
                    "displayType": 0
                }
            ],
            "energyProductionLifetimeOffset": 0,
            "powerConsumptionTotalStateSensor": {
                "displayType": 0
            },
            "powerConsumptionTotalLevelSensors": [
                {
                    "powerLevel": 0,
                    "displayType": 0
                }
            ],
            "energyConsumptionTotalLifetimeOffset": 0,
            "energyConsumptionTotalStateSensor": {
                "displayType": 0
            },
            "energyConsumptionTotalLevelSensors": [
                {
                    "energyLevel": 0,
                    "displayType": 0
                }
            ],
            "powerConsumptionNetStateSensor": {
                "displayType": 0
            },
            "powerConsumptionNetLevelSensors": [
                {
                    "name": ">5Kw to Net",
                    "compareMode": 0,
                    "powerLevel": -5000,
                    "displayType": 3
                },
                {
                    "name": ">4.4Kw to Net",
                    "compareMode": 0,
                    "powerLevel": -4400,
                    "displayType": 3
                }
            ],
            "energyConsumptionNetLifetimeOffset": 0,
            "energyConsumptionNetStateSensor": {
                "displayType": 0
            },
            "energyConsumptionNetLevelSensors": [
                {
                    "energyLevel": 0,
                    "displayType": 0
                }
            ],
            "enchargeProfileControl": [
                {
                    "profile": "backup",
                    "displayType": 0
                }
            ],
            "enchargeProfileSensors": [
                {
                    "displayType": 0
                }
            ],
            "enchargeStateSensor": {
                "displayType": 0
            },
            "enchargeGridModeSensors": [
                {
                    "displayType": 0
                }
            ],
            "enchargeBackupLevelSensors": [
                {
                    "displayType": 0
                }
            ],
            "enpowerGridStateControl": {
                "displayType": 0
            },
            "enpowerGridStateSensor": {
                "displayType": 0
            },
            "enpowerGridModeSensors": [
                {
                    "displayType": 0
                }
            ],
            "enpowerDryContactsControl": false,
            "enpowerDryContactsSensors": false,
            "solarGridModeSensors": [
                {
                    "displayType": 0
                }
            ],
            "generatorStateControl": {
                "displayType": 0
            },
            "generatorStateSensor": {
                "displayType": 0
            },
            "generatorModeControl": [
                {
                    "mode": "off",
                    "displayType": 0
                }
            ],
            "generatorModeSensors": [
                {
                    "displayType": 0
                }
            ],
            "dataRefreshControl": {
                "displayType": 0
            },
            "dataRefreshSensor": {
                "displayType": 0
            },
            "metersDataRefreshTime": 1000,
            "productionDataRefreshTime": 1000,
            "liveDataRefreshTime": 1000,
            "enableDebugMode": true,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "restFul": {
                "enable": false,
                "debug": false
            },
            "mqtt": {
                "enable": false,
                "debug": false,
                "auth": false
            }
        },
        {
            "envoyFirmware7xx": false,
            "envoyFirmware7xxTokenGenerationMode": 0,
            "supportPlcLevel": false,
            "plcLevelControl": {
                "displayType": 0
            },
            "supportPowerProductionState": false,
            "powerProductionStateControl": {
                "displayType": 0
            },
            "powerProductionStateSensor": {
                "displayType": 0
            },
            "powerProductionLevelSensors": [
                {
                    "displayType": 0
                }
            ],
            "energyProductionStateSensor": {
                "displayType": 0
            },
            "energyProductionLevelSensors": [
                {
                    "displayType": 0
                }
            ],
            "powerConsumptionTotalStateSensor": {
                "displayType": 0
            },
            "powerConsumptionTotalLevelSensors": [
                {
                    "displayType": 0
                }
            ],
            "energyConsumptionTotalStateSensor": {
                "displayType": 0
            },
            "energyConsumptionTotalLevelSensors": [
                {
                    "displayType": 0
                }
            ],
            "powerConsumptionNetStateSensor": {
                "displayType": 0
            },
            "powerConsumptionNetLevelSensors": [
                {
                    "displayType": 0
                }
            ],
            "energyConsumptionNetStateSensor": {
                "displayType": 0
            },
            "energyConsumptionNetLevelSensors": [
                {
                    "displayType": 0
                }
            ],
            "enchargeProfileControl": [
                {
                    "profile": "backup",
                    "displayType": 0
                }
            ],
            "enchargeProfileSensors": [
                {
                    "displayType": 0
                }
            ],
            "enchargeStateSensor": {
                "displayType": 0
            },
            "enchargeGridModeSensors": [
                {
                    "displayType": 0
                }
            ],
            "enchargeBackupLevelSensors": [
                {
                    "displayType": 0
                }
            ],
            "enpowerGridStateControl": {
                "displayType": 0
            },
            "enpowerGridStateSensor": {
                "displayType": 0
            },
            "enpowerGridModeSensors": [
                {
                    "displayType": 0
                }
            ],
            "enpowerDryContactsControl": false,
            "enpowerDryContactsSensors": false,
            "solarGridModeSensors": [
                {
                    "displayType": 0
                }
            ],
            "generatorStateControl": {
                "displayType": 0
            },
            "generatorStateSensor": {
                "displayType": 0
            },
            "generatorModeControl": [
                {
                    "mode": "off",
                    "displayType": 0
                }
            ],
            "generatorModeSensors": [
                {
                    "displayType": 0
                }
            ],
            "dataRefreshControl": {
                "displayType": 0
            },
            "dataRefreshSensor": {
                "displayType": 0
            },
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "restFul": {
                "enable": false,
                "debug": false
            },
            "mqtt": {
                "enable": false,
                "debug": false,
                "auth": false
            }
        }
    ],
    "_bridge": {
        "username": "0E:3B:59:9C:9E:4E",
        "port": 55365
    },
    "platform": "enphaseEnvoy"
}

**Comment by grzegorz914** [comment]
Pleas do not use special characters in `name` like `>` and `.`

**Comment by grzegorz914** [comment]
Reference error is fixed in 9.5.1

**Comment by grzegorz914** [comment]
Please change refresh time, the time is in seconds, You have set 1000 sec, I think this is Your problem, because the data is refresh every 1000 seconds.

**Comment by rrebel01** [comment]
Let me try, those used to be ms in the past?

**Comment by grzegorz914** [comment]
Was long ago changed to sec.

**Comment by rrebel01** [comment]
Seems we are getting there. just get this error in the logs:
Device: 192.168.250.53 Envoy Rebel, Impulse generator: Error: Update production ct error: timeout of 20000ms exceeded

**Comment by grzegorz914** [comment]
To many request to Envoy, please increase refresh time for production. Envoy have very poor CPU.
