### ISSUE TITLE
Error: Check JWT token error: Get JWT token error:

### ISSUE THREAD

**Issue by CaptainPic** [grzegorz914/homebridge-enphase-envoy#165]
I'm also seeing this JWT token error in Homebridge logs and no response in Homekit.   This started fairly recently.

[homebridge-enphase-envoy.log (9).txt](https://github.com/user-attachments/files/17894950/homebridge-enphase-envoy.log.9.txt)

**Comment by grzegorz914** [comment]
Are you sure You have correct credentials data and serial number set in config?

**Comment by grzegorz914** [comment]
try 9.5.2-beta.7 and let me know please

**Comment by grzegorz914** [comment]
still the issue exist with latest release ?
