### ISSUE TITLE
Brightness warning

### ISSUE THREAD

**Issue by timsnaj** [grzegorz914/homebridge-enphase-envoy#168]
Getting the following warning:

[02/12/2024, 16:26:58] [homebridge-enphase-envoy] This plugin generated a warning from the characteristic 'Brightness': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.

**Comment by grzegorz914** [comment]
Post debug log please

**Comment by timsnaj** [comment]
Warning went away after defining a few sensors, hitting some errors now: 
Error: Start error: Error: Update power production state error: Request failed with status code 401, trying again.
See attached debug log
[homebridge-enphase-envoy.log.txt](https://github.com/user-attachments/files/17981513/homebridge-enphase-envoy.log.txt)

**Comment by grzegorz914** [comment]
Disable power production control in plugin config, this options require installer credentials data

**Comment by timsnaj** [comment]
Same error in PLC. Device: envoy.local Zonnepanelen, Error: Start error: Error: Update plc level error: Request failed with status code 401, trying again.

**Comment by grzegorz914** [comment]
Yes, disable it

**Comment by grzegorz914** [comment]
Both issue fixed in 9.6.4

**Comment by timsnaj** [comment]
Ok.thx
