### ISSUE TITLE
New Error with 5.2.20

### ISSUE THREAD

**Issue by cscott365** [grzegorz914/homebridge-enphase-envoy#39]
Ensemble Error back with 5.2.20:

Device: 192.168.7.200 Envoy-IQ, update Device state error: TypeError: Cannot read property '<serial number removed>' of undefined
    at envoyDevice.updateDeviceState (/usr/lib/node_modules/homebridge-enphase-envoy/index.js:3966:93)

**Comment by cscott365** [comment]
Also exists in 5.2.18 but OK in 5.2.16.

**Comment by grzegorz914** [comment]
Try 5.2.21

**Comment by cscott365** [comment]
Looks good again. Thank you!
