### ISSUE TITLE
401 after update to latest plugin - using envoy-s firmware D5.0.62 (5e57a9)

### ISSUE THREAD

**Issue by MchlLyn** [grzegorz914/homebridge-enphase-envoy#48]
Plugin is configured with the installer password (which stills works when browsing to the web interface of the envoy-s). Everything worked up untill the latest plugin update today (29-03-2022), which somehow broke the installer login/authentication.

Logging:

`Device: 10.0.0.222 Envoy-S, microinvertersData error: Error: Request failed with status code 401
    at createError (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function: toJSON]`

**Comment by MchlLyn** [comment]
Ps. via the enlighten toolkit app the firmware D5.0.62 (5e57a9) is up-to-date...there are seemingly no newer firmwares available for my device.

**Comment by grzegorz914** [comment]
Hmm, same firmware on my Envoy all working without any error.
Can you post the config.json?

**Comment by MchlLyn** [comment]
Yes, it's strange...everything worked, I only updated the plugin and noticed the error. I've also tried by removing the installer password but I'm still getting the 401 so i've put it back.

This is my config (installer pwd removed):

`        {
            "devices": [
                {
                    "name": "Envoy-S",
                    "host": "10.0.0.222",
                    "disableLogInfo": true,
                    "enableDebugMode": false,
                    "installerPasswd": "<redacted>",
                    "entrezAuth": false,
                    "powerProductionMaxDetected": 4500,
                    "energyProductionLifetimeOffset": 0,
                    "powerConsumptionTotalMaxDetected": 0,
                    "energyConsumptionTotalLifetimeOffset": 0,
                    "powerConsumptionNetMaxDetected": 0,
                    "energyConsumptionNetLifetimeOffset": 0,
                    "enableMqtt": false,
                    "mqttAuth": false,
                    "mqttDebug": false
                }
            ],
            "platform": "enphaseEnvoy"
        },`

**Comment by grzegorz914** [comment]
Microinverters data need envoyPasswd not installerPasswd, if you don't change it please leave the field in config empty in other case need to be set. Also try to restart plugin or HB again.

**Comment by MchlLyn** [comment]
I just reverted to version 5.6.2 and everything works, with or without the installer password.
Then I installed 5.6.3 and it does not work, with or without the installer password.

This is the debug output and it is receiving data, but stills end with the 401 error (sorry for the long output...i do not see an option to attach logfiles):

[3/29/2022, 12:56:32 PM] [enphaseEnvoy] Device: 10.0.0.222 Envoy-S, debug homeData: {
  "software_build_epoch": 1622651920,
  "is_nonvoy": false,
  "db_size": "6 MB",
  "db_percent_full": "1",
  "timezone": "Europe/Brussels",
  "current_date": "03/29/2022",
  "current_time": "12:56",
  "network": {
    "web_comm": true,
    "ever_reported_to_enlighten": true,
    "last_enlighten_report_time": 1648550144,
    "primary_interface": "eth0",
    "interfaces": [
      {
        "type": "ethernet",
        "interface": "eth0",
        "mac": "00:1D:C0:6E:1E:C3",
        "dhcp": true,
        "ip": "10.0.0.222",
        "signal_strength": 1,
        "signal_strength_max": 1,
        "carrier": true
      },
      {
        "signal_strength": 0,
        "signal_strength_max": 0,
        "type": "wifi",
        "interface": "wlan0",
        "mac": "28:EC:9A:A8:47:28",
        "dhcp": true,
        "ip": null,
        "carrier": false,
        "supported": true,
        "present": true,
        "configured": false,
        "status": "connecting"
      }
    ]
  },
  "tariff": "none",
  "comm": {
    "num": 14,
    "level": 5,
    "pcu": {
      "num": 13,
      "level": 5
    },
    "acb": {
      "num": 0,
      "level": 0
    },
    "nsrb": {
      "num": 1,
      "level": 5
    }
  },
  "alerts": [],
  "update_status": "satisfied"
}
[3/29/2022, 12:56:32 PM] [enphaseEnvoy] Device: 10.0.0.222 Envoy-S, debug inventoryData: [
  {
    "type": "PCU",
    "devices": [
      {
        "part_num": "800-00630-r02",
        "installed": "1640346635",
        "serial_num": "121909058555",
        "device_status": [
          "envoy.global.ok"
        ],
        "last_rpt_date": "1648551076",
        "admin_state": 2,
        "dev_type": 1,
        "created_date": "1640346635",
        "img_load_date": "1646040912",
        "img_pnum_running": "520-00082-r01-v04.28.07",
        "ptpn": "540-00134-r01-v04.28.02",
        "chaneid": 1627390225,
        "device_control": [
          {
            "gficlearset": false
          }
        ],
        "producing": true,
        "communicating": true,
        "provisioned": true,
        "operating": true
      },
      {
        "part_num": "800-00630-r02",
        "installed": "1640346637",
        "serial_num": "121909058513",
        "device_status": [
          "envoy.global.ok"
        ],
        "last_rpt_date": "1648551078",
        "admin_state": 2,
        "dev_type": 1,
        "created_date": "1640346637",
        "img_load_date": "1646040912",
        "img_pnum_running": "520-00082-r01-v04.28.07",
        "ptpn": "540-00134-r01-v04.28.02",
        "chaneid": 1627390481,
        "device_control": [
          {
            "gficlearset": false
          }
        ],
        "producing": true,
        "communicating": true,
        "provisioned": true,
        "operating": true
      },
      {
        "part_num": "800-00630-r02",
        "installed": "1640346638",
        "serial_num": "121915066527",
        "device_status": [
          "envoy.global.ok"
        ],
        "last_rpt_date": "1648551081",
        "admin_state": 2,
        "dev_type": 1,
        "created_date": "1640346638",
        "img_load_date": "1646040912",
        "img_pnum_running": "520-00082-r01-v04.28.07",
        "ptpn": "540-00134-r01-v04.28.02",
        "chaneid": 1627390737,
        "device_control": [
          {
            "gficlearset": false
          }
        ],
        "producing": true,
        "communicating": true,
        "provisioned": true,
        "operating": true
      },
      {
        "part_num": "800-00630-r02",
        "installed": "1640346639",
        "serial_num": "121915066482",
        "device_status": [
          "envoy.global.ok"
        ],
        "last_rpt_date": "1648551081",
        "admin_state": 2,
        "dev_type": 1,
        "created_date": "1640346639",
        "img_load_date": "1646040912",
        "img_pnum_running": "520-00082-r01-v04.28.07",
        "ptpn": "540-00134-r01-v04.28.02",
        "chaneid": 1627390993,
        "device_control": [
          {
            "gficlearset": false
          }
        ],
        "producing": true,
        "communicating": true,
        "provisioned": true,
        "operating": true
      },
      {
        "part_num": "800-00630-r02",
        "installed": "1640346641",
        "serial_num": "121915093345",
        "device_status": [
          "envoy.global.ok"
        ],
        "last_rpt_date": "1648551084",
        "admin_state": 2,
        "dev_type": 1,
        "created_date": "1640346641",
        "img_load_date": "1646040912",
        "img_pnum_running": "520-00082-r01-v04.28.07",
        "ptpn": "540-00134-r01-v04.28.02",
        "chaneid": 1627391249,
        "device_control": [
          {
            "gficlearset": false
          }
        ],
        "producing": true,
        "communicating": true,
        "provisioned": true,
        "operating": true
      },
      {
        "part_num": "800-00630-r02",
        "installed": "1640346643",
        "serial_num": "121915093731",
        "device_status": [
          "envoy.global.ok"
        ],
        "last_rpt_date": "1648551086",
        "admin_state": 2,
        "dev_type": 1,
        "created_date": "1640346643",
        "img_load_date": "1646040912",
        "img_pnum_running": "520-00082-r01-v04.28.07",
        "ptpn": "540-00134-r01-v04.28.02",
        "chaneid": 1627391505,
        "device_control": [
          {
            "gficlearset": false
          }
        ],
        "producing": true,
        "communicating": true,
        "provisioned": true,
        "operating": true
      },
      {
        "part_num": "800-00630-r02",
        "installed": "1640346645",
        "serial_num": "121915101114",
        "device_status": [
          "envoy.global.ok"
        ],
        "last_rpt_date": "1648551087",
        "admin_state": 2,
        "dev_type": 1,
        "created_date": "1640346645",
        "img_load_date": "1646040912",
        "img_pnum_running": "520-00082-r01-v04.28.07",
        "ptpn": "540-00134-r01-v04.28.02",
        "chaneid": 1627391761,
        "device_control": [
          {
            "gficlearset": false
          }
        ],
        "producing": true,
        "communicating": true,
        "provisioned": true,
        "operating": true
      },
      {
        "part_num": "800-00630-r02",
        "installed": "1640346646",
        "serial_num": "121915075747",
        "device_status": [
          "envoy.global.ok"
        ],
        "last_rpt_date": "1648551089",
        "admin_state": 2,
        "dev_type": 1,
        "created_date": "1640346646",
        "img_load_date": "1646040912",
        "img_pnum_running": "520-00082-r01-v04.28.07",
        "ptpn": "540-00134-r01-v04.28.02",
        "chaneid": 1627392017,
        "device_control": [
          {
            "gficlearset": false
          }
        ],
        "producing": true,
        "communicating": true,
        "provisioned": true,
        "operating": true
      },
      {
        "part_num": "800-00630-r02",
        "installed": "1640346647",
        "serial_num": "121915093191",
        "device_status": [
          "envoy.global.ok"
        ],
        "last_rpt_date": "1648551091",
        "admin_state": 2,
        "dev_type": 1,
        "created_date": "1640346647",
        "img_load_date": "1646040912",
        "img_pnum_running": "520-00082-r01-v04.28.07",
        "ptpn": "540-00134-r01-v04.28.02",
        "chaneid": 1627392273,
        "device_control": [
          {
            "gficlearset": false
          }
        ],
        "producing": true,
        "communicating": true,
        "provisioned": true,
        "operating": true
      },
      {
        "part_num": "800-00630-r02",
        "installed": "1640346648",
        "serial_num": "121915093349",
        "device_status": [
          "envoy.global.ok"
        ],
        "last_rpt_date": "1648551093",
        "admin_state": 2,
        "dev_type": 1,
        "created_date": "1640346648",
        "img_load_date": "1646040912",
        "img_pnum_running": "520-00082-r01-v04.28.07",
        "ptpn": "540-00134-r01-v04.28.02",
        "chaneid": 1627392529,
        "device_control": [
          {
            "gficlearset": false
          }
        ],
        "producing": true,
        "communicating": true,
        "provisioned": true,
        "operating": true
      },
      {
        "part_num": "800-00630-r02",
        "installed": "1640346650",
        "serial_num": "121915093651",
        "device_status": [
          "envoy.global.ok"
        ],
        "last_rpt_date": "1648551094",
        "admin_state": 2,
        "dev_type": 1,
        "created_date": "1640346650",
        "img_load_date": "1646040912",
        "img_pnum_running": "520-00082-r01-v04.28.07",
        "ptpn": "540-00134-r01-v04.28.02",
        "chaneid": 1627392785,
        "device_control": [
          {
            "gficlearset": false
          }
        ],
        "producing": true,
        "communicating": true,
        "provisioned": true,
        "operating": true
      },
      {
        "part_num": "800-00630-r02",
        "installed": "1640346652",
        "serial_num": "121915093346",
        "device_status": [
          "envoy.global.ok"
        ],
        "last_rpt_date": "1648551097",
        "admin_state": 2,
        "dev_type": 1,
        "created_date": "1640346652",
        "img_load_date": "1646040912",
        "img_pnum_running": "520-00082-r01-v04.28.07",
        "ptpn": "540-00134-r01-v04.28.02",
        "chaneid": 1627393041,
        "device_control": [
          {
            "gficlearset": false
          }
        ],
        "producing": true,
        "communicating": true,
        "provisioned": true,
        "operating": true
      },
      {
        "part_num": "800-01102-r02",
        "installed": "1640346653",
        "serial_num": "121903070202",
        "device_status": [
          "envoy.global.ok"
        ],
        "last_rpt_date": "1648551099",
        "admin_state": 2,
        "dev_type": 1,
        "created_date": "1640346653",
        "img_load_date": "1646045517",
        "img_pnum_running": "520-00082-r01-v04.28.07",
        "ptpn": "540-00145-r01-v04.28.02",
        "chaneid": 1627393297,
        "device_control": [
          {
            "gficlearset": false
          }
        ],
        "producing": true,
        "communicating": true,
        "provisioned": true,
        "operating": true
      }
    ]
  },
  {
    "type": "ACB",
    "devices": []
  },
  {
    "type": "NSRB",
    "devices": [
      {
        "part_num": "800-00598-r04",
        "installed": "1640346654",
        "serial_num": "121902062748",
        "device_status": [
          "envoy.global.ok"
        ],
        "last_rpt_date": "1648551100",
        "admin_state": 2,
        "dev_type": 12,
        "created_date": "1640346654",
        "img_load_date": "1522376696",
        "img_pnum_running": "520-00086-r01-v02.12.07",
        "ptpn": "540-00139-r01-v02.12.00",
        "chaneid": 1811939601,
        "device_control": [
          {
            "gficlearset": false
          }
        ],
        "producing": false,
        "communicating": true,
        "provisioned": true,
        "operating": true,
        "relay": "closed",
        "reason_code": -1,
        "reason": "ok",
        "line-count": 1,
        "line1-connected": true,
        "line2-connected": false,
        "line3-connected": false
      }
    ]
  }
]
[3/29/2022, 12:56:33 PM] [enphaseEnvoy] Device: 10.0.0.222 Envoy-S, debug productionCtData: {
  "production": [
    {
      "type": "inverters",
      "activeCount": 13,
      "readingTime": 1648551100,
      "wNow": 2024,
      "whLifetime": 890032
    }
  ],
  "storage": [
    {
      "type": "acb",
      "activeCount": 0,
      "readingTime": 0,
      "wNow": 0,
      "whNow": 0,
      "state": "idle"
    }
  ]
}
[3/29/2022, 12:56:33 PM] [enphaseEnvoy] Device: 10.0.0.222 Envoy-S, microinvertersData error: Error: Request failed with status code 401
    at createError (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function: toJSON]

**Comment by grzegorz914** [comment]
Please try 3.6.4-beta.0 and let me know

**Comment by MchlLyn** [comment]
Unfortunately no success, still getting the 401.

**Comment by grzegorz914** [comment]
arę you sure You don't changed envoyPasswd?

**Comment by MchlLyn** [comment]
Not that I'm aware. My envoy-s was broken and replaced in December. I installed it myself and most definitely did not change any password on the new one.

If it was changed, would the old plugin version 5.6.2 still work?

**Comment by grzegorz914** [comment]
OK, probably fixed wit 3.6.4-beta.1

**Comment by MchlLyn** [comment]
Yes! 3.6.4-beta.1 fixed it :)
Thanks!

**Comment by MchlLyn** [comment]
ps. I've closed this, assuming I should once it's fixed :-)

**Comment by CassiusPacheco** [comment]
I was having this issue yesterday and this update fixed, thanks!

On another note, is there a place where I can find more details about which piece of data I should use in order to trigger some automation? For example, "Do X when the production surplus is higher than Y"?

Thanks again for the plugin
