### ISSUE TITLE
Recent Code Cleanup Appears To Have Broken Power Reporting In HomeKit

### ISSUE THREAD

**Issue by mopac01** [grzegorz914/homebridge-enphase-envoy#55]
All inverters show 0W all day.  Power and Energy for array in total is also incorrect.  This appears to have started after the most recent plugin update which I believe was noted as code cleanup.  (I'm not 100% positive of this as there have been a number of plugin updates over the last week or so.  I *might* have one or two updates ago.)

**Comment by grzegorz914** [comment]
Please enable debug mode and get the log, here is all ok.
