### ISSUE TITLE
Help Wanted! Newb can't figure out how to generate installer password...

### ISSUE THREAD

**Issue by asander85** [grzegorz914/homebridge-enphase-envoy#56]
I am a total newb and am having difficulty. I see the instructions for generating the installer password, but When I paste the python code into PowerShell I get errors and no password. Can someone help me out? Thanks so much!!

**Comment by asander85** [comment]
Also. for the IP/Hostname in the Homebridge settings, am I supposed to use the IP address of the Envoy Gateway or the URL for the installer page?

**Comment by grzegorz914** [comment]
1. To generate installer password you need download android app from the site. 
2. Is or Hostname of envoy not.

**Comment by grzegorz914** [comment]
in 5.9.0 installer password is generated automatically
