### ISSUE TITLE
Parsing Error noticed today

### ISSUE THREAD

**Issue by djxplor** [grzegorz914/homebridge-enphase-envoy#59]
I'm seeing the following error in my HomeAssistant logs this morning

08/11/2022, 10:12:38] [enphaseEnvoy] Device: 192.168.0.8 Envoy-S, home error: Error: Parse Error: Content-Length can't be present with Transfer-Encoding, reconnect in 15s.

Are others seeing the same thing. Enphase gateway is running fine and is reporting to enphase site.

**Comment by grzegorz914** [comment]
Still this issue exist?

**Comment by djxplor** [comment]
Have just checked and is fine again now
