### ISSUE TITLE
Can't find accessory code for Envoy after bridge is added to Apple Home

### ISSUE THREAD

**Issue by Coder84619** [grzegorz914/homebridge-enphase-envoy#62]
I was using HOOBS with the Envoy plugin, and it was working great. I'm rebuilding everything in native Homebridge. I got the Envoy plugin installed as a child bridge, and added the bridge to the Apple Home app. The bridge shows up in Home Controller. However, when I go to add the Envoy accessory in the Home app, it's asking for a pin or QR code. 

The "setup code" in the Homebridge logs that immediately follows the Envoy log entries (e.g. 777-66-555) is NOT accepted by the Home app when tapping on the Envoy accessory. 777-66-555 is the same code as the primary Homebridge bridge, which I'm not using (all child bridges). So I'm confused which code I need when adding the Envoy accessory. 

[01/12/2022, 10:57:29] Please add [Envoy-S A2B7] manually in Home app. Setup Code: 777-66-555

**Comment by grzegorz914** [comment]
The code is always the Homebridge code.
