### ISSUE TITLE
Version 6 - beta test for Envoy with firmware 7.x.x 

### ISSUE THREAD

**Issue by grzegorz914** [grzegorz914/homebridge-enphase-envoy#63]
I have published v6.0.0-beta to test.
In Authorization section You can enable support for FW. 7xx.x and paste your generated token.
This test version may not working correct at this time, it is only to test correct login to envoy.
I don’t have Envoy with FW 7.x.x and all your help  and test will be very helpful for me.
For test please also enable debug mode and always post the log.

This will close #57 #61 #60 #

**Comment by NoSnow3** [comment]
I am on V7.0.107 Firmware, Happy to help beta test.
First Project I've attempted to help with so go easy.

Attempted to use Un-Commisioned Token, Feedback:

Device: 192.168.0.41 Envoy-S, inventory error: AxiosError: Request failed with status code 401, reconnect in 15s.

Used token fed via "https://enlighten.enphaseenergy.com/entrez-auth-token?serial_num={}"
(Long Term Tokens)
Feedback:

Device: 192.168.0.41 Envoy-S, inventory error: AxiosError: Request failed with status code 401, reconnect in 15s.

Same errors.

Like I said I'm new not much involved with any sorting coding, Unsure how to correctly find logs.
If anyone can brief me i will certainly find them

From a user sadly missing V5.x.xxx Firmware

**Comment by grzegorz914** [comment]
@NoSnow3 
Thanks for test but please enable debug in plugin settings advanced section and post the complete log.  As i see your error is from other section, looks like token login is working.

**Comment by NoSnow3** [comment]
[homebridge.log.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10201744/homebridge.log.txt)

Hoping this is what you are looking for.

**Comment by grzegorz914** [comment]
@NoSnow3 
pushed beta.7 to test, also please test again with the log.

It will be very helpful for me if someone can get me the remote access to Envoy with FW 7.x.x.

**Comment by NoSnow3** [comment]
[HomeBridge Beta7 Log.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10201787/HomeBridge.Beta7.Log.txt)


New Log...

"Device: 192.168.0.41 Envoy-S, inventory error: Error: self signed certificate, reconnect in 15s."

Regards Remote access. To the actual Envoy? unsure on how we can do that envoy itself

**Comment by grzegorz914** [comment]
beta.8 pushed, try again

**Comment by NoSnow3** [comment]
[homebridge Beta8 Log.log.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10201796/homebridge.Beta8.Log.log.txt)

"inventory error: TypeError: this.digestAuthInstaller is not a function, reconnect in 15s."

**Comment by grzegorz914** [comment]
again beta.10

**Comment by NoSnow3** [comment]
[homebridge Beta10 Log.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10201802/homebridge.Beta10.Log.txt)

"Envoy-S, inventory error: Error: self signed certificate, reconnect in 15s."

**Comment by grzegorz914** [comment]
OK, try beta.11

**Comment by NoSnow3** [comment]
[homebridge Beta11 Log.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10201825/homebridge.Beta11.Log.txt)

Same again,

"inventory error: Error: self signed certificate, reconnect in 15s."

**Comment by grzegorz914** [comment]
beta.14 ready

**Comment by NoSnow3** [comment]
[homebridge Beta14 Log.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10201866/homebridge.Beta14.Log.txt)

"Envoy-S, inventory error: AxiosError: Request failed with status code 401, reconnect in 15s."

Seems to take longer to error this time

**Comment by grzegorz914** [comment]
try beta.16

**Comment by NoSnow3** [comment]
[homebridge Beta15 Log.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10201965/homebridge.Beta15.Log.txt)

"Envoy-S, meters error: AxiosError: Request failed with status code 401, reconnect in 15s."

Beta 15 was all that available

**Comment by NoSnow3** [comment]
[homebridge Beta16 Log.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10202011/homebridge.Beta16.Log.txt)

"meters error: AxiosError: Request failed with status code 401, reconnect in 15s."

**Comment by NoSnow3** [comment]
I Changed token from the shorter timed one that was on the "https://entrez.enphaseenergy.com/entrez_tokens" Link

To my longer Validated Token on "https://enlighten.enphaseenergy.com/entrez-auth-token?serial_num={}"

This time the Log is showing readouts from the envoy but still showing error.

" power mode error: AxiosError: Request failed with status code 401, reconnect in 15s."

[homebridge Beta16.2 Log.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10202028/homebridge.Beta16.2.Log.txt)

**Comment by grzegorz914** [comment]
ok looks better now, try beta.22

**Comment by NoSnow3** [comment]
[homebridge Beta22 Log.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10202088/homebridge.Beta22.Log.txt)


Looking better, Thought i had seen an error but its refreshing to fast to catch it

**Comment by NoSnow3** [comment]
Ah found it,

"[11/12/2022, 11:57:04] [homebridge-enphase-envoy] Device: 192.168.0.41 Envoy-S, home error: TypeError: Cannot read properties of undefined (reading 'updateCharacteristic'), reconnect in 15s."

**Comment by grzegorz914** [comment]
try beta 23

**Comment by NoSnow3** [comment]
Scrap the above as regards to errors

[homebridge Beta23.2 Log.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10202230/homebridge.Beta23.2.Log.txt)


"[11/12/2022, 13:01:52] [homebridge-enphase-envoy] Device: 192.168.0.41 Envoy-S, home error: TypeError: Cannot read properties of undefined (reading 'updateCharacteristic'), reconnect in 15s."

**Comment by NoSnow3** [comment]
No errors spotted. 

Still Can not see Devices in Eve or Controller at this moment.

**Comment by grzegorz914** [comment]
Arę you added it to the HomeKit app

**Comment by grzegorz914** [comment]
you need add this accessory ti the home.app first

**Comment by NoSnow3** [comment]
Can confirm i have done this.
![IMG_3348](https://user-images.githubusercontent.com/47488734/206909887-dcc408f0-daba-4708-8f4b-cd8e0d1db4ce.PNG)

**Comment by grzegorz914** [comment]
this is bridge not the accessory itself, look here https://github.com/grzegorz914/homebridge-enphase-envoy/wiki#adding-to-homekit

**Comment by grzegorz914** [comment]
beta.25 pushed to test

**Comment by NoSnow3** [comment]
Updateded but still can not find the accessory when scanning once the child bridge is added

**Comment by grzegorz914** [comment]
Can you post the log after update to b.25

Also try this if can not find the accessory https://github.com/grzegorz914/homebridge-enphase-envoy/wiki#troubleshooting

**Comment by NoSnow3** [comment]
Followed Troubleshooting, No results as of yet.
[homebridge Beta 25.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10202505/homebridge.Beta.25.txt)


Log attached.

**Comment by NoSnow3** [comment]
[homebridge Beta 26 Log.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10202585/homebridge.Beta.26.Log.txt)

Log Attached

**Comment by grzegorz914** [comment]
Nice, probably final beta 27 ready

**Comment by NoSnow3** [comment]
Downloading, Still yet to see in Eve or controller, Scratching my head on that one

**Comment by NoSnow3** [comment]
"Device: 192.168.0.41 Envoy-S, ensemble inventory error: TypeError: Cannot read properties of undefined (reading 'devices'), reconnect in 15s"

[homebridge Beta 27.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10202597/homebridge.Beta.27.txt)

**Comment by grzegorz914** [comment]
28 ready

**Comment by NoSnow3** [comment]
Might be an ios16 issue hold on

**Comment by grzegorz914** [comment]
No,  try this https://github.com/grzegorz914/homebridge-enphase-envoy/wiki#troubleshooting and after this restart whole homebridge then try add accessory again, no need add bridge to home.app

**Comment by grzegorz914** [comment]
any log from beta.28

**Comment by NoSnow3** [comment]
[homebridge Beta 28 Log.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10202724/homebridge.Beta.28.Log.txt)


Same Error again

**Comment by grzegorz914** [comment]
ok beta.29 ready

**Comment by NoSnow3** [comment]
[homebridge Beta 29 Log.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10202779/homebridge.Beta.29.Log.txt)

No immediate errors

**Comment by grzegorz914** [comment]
Nice, ready to publish release.
Many thanks for testing and patience.

**Comment by NoSnow3** [comment]
No problem, still struggling with displaying in eve/controller

**Comment by grzegorz914** [comment]
This must be added to Home.app first

**Comment by NoSnow3** [comment]
I can not add just the accessories only the bridge.

**Comment by grzegorz914** [comment]
May be try to change the name in plugin Config

**Comment by grzegorz914** [comment]
Also try to clear Homebridge cashe

**Comment by NoSnow3** [comment]
Cleared cache and added using iOS 15.5. Shows on Eve and Controller now

**Comment by grzegorz914** [comment]
Nice.

**Comment by grzegorz914** [comment]
v6.0.0 released
