### ISSUE TITLE
Enphase changed Energy Lifetime counter during update to firmware 7

### ISSUE THREAD

**Issue by cbrandlehner** [grzegorz914/homebridge-enphase-envoy#72]
I was puzzled by this log entry:
`[1/14/2023, 11:47:01 AM] [homebridge-enphase-envoy] This plugin generated a warning from the characteristic 'Energy lifetime': characteristic was supplied illegal value: number -2779.839 exceeded minimum of 0. See https://homebridge.io/w/JtMGR for more info.`

I tried to find the root cause of the problem and had a look into my Grafana dashboard. In the backend, I use an InfluxDB to store data I retrieve from the Envoy.
Look at this screenshot:
![Bildschirm­foto 2023-01-14 um 11 52 20](https://user-images.githubusercontent.com/10800971/212468456-c0e9c365-ef6d-4cf7-b15d-deb23d00108d.png)

I shows that Enphase reset the "Energy Lifetime" counter to a large negative number during the update to firmware 7.

This is not a bug with the plugin but I want the community to be aware that this could happen during upgrade.

**Comment by grzegorz914** [comment]
I will add workaround for this issue in next release.
