### ISSUE TITLE
6.3.2 don't work with firmware 7

### ISSUE THREAD

**Issue by BenouGui** [grzegorz914/homebridge-enphase-envoy#73]
Hello, 
6.3.2 don't work with firmware 7 

Thank

**Comment by grzegorz914** [comment]
6.3.1 works?

**Comment by BenouGui** [comment]
yes

**Comment by grzegorz914** [comment]
can you post debug

**Comment by BenouGui** [comment]
[
[homebridge.log-28.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10420017/homebridge.log-28.txt)
]

**Comment by grzegorz914** [comment]
try 6.4.0-beta.8 please

**Comment by BenouGui** [comment]
[homebridge.log-29.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10420154/homebridge.log-29.txt)

nok :/

**Comment by grzegorz914** [comment]
try .11

**Comment by BenouGui** [comment]
[homebridge.log-30.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10420168/homebridge.log-30.txt)
 it ok I think

**Comment by grzegorz914** [comment]
OK, can you get the whole log after plugin restart, I want to compare with other 7.x.x firmware, looks like Enphase publish different local api in different 7.x.x firmwares

**Comment by BenouGui** [comment]
[homebridge.log-31.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10420186/homebridge.log-31.txt)

**Comment by grzegorz914** [comment]
6.4.0 released
