### ISSUE TITLE
Parse Error: Content-Length can't be present with Transfer-Encoding

### ISSUE THREAD

**Issue by dstupakov** [grzegorz914/homebridge-enphase-envoy#75]
Hi,

I get the following error when trying to run your plugin. Is this a known issue, or something I can fix in the config? 

[2/2/2023, 3:15:35 PM] [homebridge-enphase-envoy] Device: envoy.local Envoy, Update home data error: Error: Parse Error: Content-Length can't be present with Transfer-Encoding, reconnect in 15s.

Thank you for your contribution.

plugin version: 6.5.3
enphase version: 5.0.49

**Comment by grzegorz914** [comment]
Post Your config Please, also  Please enable debug in plugin config advanced section and get the complete log again.

**Comment by HGordonH** [comment]
Hi - Ive started to get the same error

**Comment by grzegorz914** [comment]
I need complete debug log, Please go to plugin section advanced settings and enable debug, then save and restart plugin. Next post the complete log.

**Comment by HGordonH** [comment]
looked at the logs again and seems to be OK now, no errors. When I posted the issue there was no solar generation, there is now and error no longer shows. I’ll check again tonight and if the error comes back I’ll post the log.
