### ISSUE TITLE
Am I supposed to see data from the microinverters within the Controller App?

### ISSUE THREAD

**Issue by kvpoma** [grzegorz914/homebridge-enphase-envoy#77]
I can see on my homebridge that my microinverters are reporting, but when I go into the Controller app, all I can see is the Envoy as an accessory.  I’m not seeing any other data.  Is there something that I need to edit within the settings to get the data into the Controller app?

**Comment by grzegorz914** [comment]
Are you added this accessory to Home.app?

**Comment by kvpoma** [comment]
Have I? Yes.  Using my Homebridge HomeKit code, I added the envoy to the Home app, although I don't see it in any of my rooms

**Comment by grzegorz914** [comment]
Accessory itself will not be displayed in Apple Home.app because do not support custom characteristics, only sensors will be displayed.. 
In Controller or EVE app need to be displayed all services as Envoy, Microinverters, Meters, etc.

![IMG_0798](https://user-images.githubusercontent.com/28867813/219967861-5352b764-3999-4bf7-9e34-05d62ac7e924.png)

**Comment by kvpoma** [comment]
I understand that the data can’t be showed in HomeKit. My problem is the data isn’t showing up in the controller app like yours. All I see is the envoy. What settings do I need to configure in the homebridge plugin to have the data show in controller app?

**Comment by grzegorz914** [comment]
Can you post your Config here. What is displayed in HB log console?

**Comment by kvpoma** [comment]
<img width="1194" alt="Screenshot 2023-02-19 at 1 16 01 PM png" src="https://user-images.githubusercontent.com/68412035/219975733-a790f653-ac24-4ac3-a459-305d3b60a64e.png">

**Comment by kvpoma** [comment]
Any other info needed?

**Comment by grzegorz914** [comment]
Enable debug mode in plugin Config and get the complete log please.

**Comment by kvpoma** [comment]
[Enphaselog.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/10834368/Enphaselog.txt)
See attached

**Comment by grzegorz914** [comment]
All is correct in log and accessory Is published, are you sure you have added it correct to the Home.app, can you record video or screenshots.

**Comment by kvpoma** [comment]
https://user-images.githubusercontent.com/68412035/221431314-0731260e-e16f-4424-b1f3-e2e652899c22.MOV

**Comment by grzegorz914** [comment]
You need add the accessory itself not the bridge, in your case is not visible use this:
https://github.com/grzegorz914/homebridge-enphase-envoy/wiki#troubleshooting 
procedure to fix this and try again. If not help clear HB cache and old accessory.

**Comment by kvpoma** [comment]
Thanks for troubleshooting this for me. Could you give me the command lines to get to there?

**Comment by grzegorz914** [comment]
What so you use

**Comment by kvpoma** [comment]
RPi running homebridge

**Comment by grzegorz914** [comment]
The files are in /var/lib/Homebridge/persist/ folder, but first Try to clear casche in HB and restart complete HB

**Comment by kvpoma** [comment]
That was the ticket. Removed cached bridges fixed the issue. Consumption is showing up in Controller now. Thank you!
