### ISSUE TITLE
Plugin not working after update to V6.7.4

### ISSUE THREAD

**Issue by ahnungsbefreit** [grzegorz914/homebridge-enphase-envoy#81]
After updating to V6.7.4, the plugin is not working any more and I see every 20 secs the following error message in the log

`[37m[3/1/2023, 7:12:57 AM] [39m[36m[homebridge-enphase-envoy][39m [31mDevice: 192.168.178.132 Envoy-S, Update live data error: ReferenceError: Objest is not defined. Reconnect in 15s.[39m`

After downgrading to V6.7.3 it works again.

**Comment by grzegorz914** [comment]
Fixe asap

**Comment by ahnungsbefreit** [comment]
Just to confirm: with V6.7.5 it works again. Thanks for the quick fix!
