### ISSUE TITLE
Why is there a switch in my Envoy that is always off?

### ISSUE THREAD

**Issue by chrisjshull** [grzegorz914/homebridge-enphase-envoy#86]
<img width="412" alt="image" src="https://github.com/grzegorz914/homebridge-enphase-envoy/assets/877679/53ef365a-8b3d-4a4a-9bef-22a80c61b2b7">

What does this do?

**Comment by grzegorz914** [comment]
This show power production mode enabled/disabled.

**Comment by chrisjshull** [comment]
Why is always “off” though?

**Comment by chrisjshull** [comment]
… because my solar panels show as producing power in the enlighten app.

**Comment by grzegorz914** [comment]
Can You enable debug in plugin config advanced section, restart plugin and get the log Please.

**Comment by chrisjshull** [comment]
[homebridge.log-18.txt](https://github.com/grzegorz914/homebridge-enphase-envoy/files/11649252/homebridge.log-18.txt)

**Comment by grzegorz914** [comment]
try 6.7.34-beta.11 and please enable `Power Mode` in plugin config `Advanced Settings`

**Comment by grzegorz914** [comment]
Fixed in 7.1.0
