### ISSUE TITLE
Gateway not loading

### ISSUE THREAD

**Issue by nmeliasp** [grzegorz914/homebridge-enphase-envoy#90]
Hello looking to see how i can get past this error i am receiving. I left the IP address blank to use the defualt

Device:  xxxx Update home data error: Error: self-signed certificate. Reconnect in 15s.

**Comment by grzegorz914** [comment]
What happened if you add correct IP adress? Please also enable debug mode in plugin config advanced section and get the log.

**Comment by nmeliasp** [comment]
i still get the following if i put the IP address of the gateway. These are the logs i see after enabling degug mode: 
7/12/2023, 1:55:54 PM] [enphaseEnvoy] Device:  Solar Gateway, Update info data error: Error: getaddrinfo ENOTFOUND envoy.local. Reconnect in 15s.
[7/12/2023, 1:56:09 PM] [enphaseEnvoy] Device:  Solar Gateway, Update home data error: Error: self-signed certificate. Reconnect in 15s.

**Comment by nmeliasp** [comment]
Here is my config {
    "devices": [
        {
            "name": "Solar Gateway",
            "envoyFirmware7xx": false,
            "envoyPasswd": "xxxx",
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "enableDebugMode": true,
            "powerProductionMax": false,
            "powerProductionMaxAutoReset": 0,
            "powerProductionMaxDetected": 5400,
            "energyProductionLifetimeOffset": 0,
            "powerConsumptionTotalMax": false,
            "powerConsumptionTotalMaxAutoReset": 0,
            "powerConsumptionTotalMaxDetected": 10000,
            "energyConsumptionTotalLifetimeOffset": 0,
            "powerConsumptionNetMax": false,
            "powerConsumptionNetMaxAutoReset": 0,
            "powerConsumptionNetMaxDetected": 10000,
            "energyConsumptionNetLifetimeOffset": 0,
            "supportProductionPowerMode": false,
            "supportPlcLevel": false,
            "supportEnsembleStatus": false,
            "supportLiveData": false,
            "liveDataRefreshTime": 1000,
            "metersDataRefreshTime": 3000,
            "productionDataRefreshTime": 5000,
            "enableRestFul": false,
            "restFulPort": 3000,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttHost": "xxx",
            "mqttPort": 1883,
            "mqttPrefix": "home/envoy",
            "mqttAuth": false,
            "mqttUser": "xxxx"
        }
    ],
    "platform": "enphaseEnvoy"
}

**Comment by grzegorz914** [comment]
Please put correct IP address in config, restart plugin and get the whole debug log. Looks like your envoy is not available in network.

**Comment by nmeliasp** [comment]
i was able to get it configured, i was using firmware 7.xxx and had to get a token. However after adding the bridge into Homekit i am not finding any of the sensors? I see the sensors in Homebridge but not Homekit

**Comment by grzegorz914** [comment]
Are you read this section:
https://github.com/grzegorz914/homebridge-enphase-envoy#about-the-plugin

**Comment by nmeliasp** [comment]
Yes I used the eve app and can see the bridge but the accessories didn't come over with the bridge..

**Comment by grzegorz914** [comment]
Are you ad the accessory itself to the HomeKit.ap?

**Comment by nmeliasp** [comment]
they didnt show up in Home Kit either

**Comment by grzegorz914** [comment]
Are you read this: 
https://github.com/grzegorz914/homebridge-enphase-envoy/wiki#adding-to-homekit 
and this:
https://github.com/grzegorz914/homebridge-enphase-envoy/wiki#troubleshooting

Can you also post whole debug log after restart plugin?

**Comment by nmeliasp** [comment]
ok i got the accessories to show up in Eve now. Currently working on the top bar and i'm getting an Error on Meter Response: Moved Permanently. 

Any idea what this error means?

**Comment by grzegorz914** [comment]
I can no help you one debug log, I need to know what happened in your system. Go to plugin settings Advanced Section and enable Debug Mode. Restart plugin and get the whole log.

**Comment by grzegorz914** [comment]
TopBar is not working with firmware 7.x.x
