### ISSUE TITLE
Device not displayed in HomeKit

### ISSUE THREAD

**Issue by jorisdebruin2** [grzegorz914/homebridge-enphase-envoy#96]
I did this but I still don't see anything in HomeKit.
some other ideas thanks 

If for some reason the device is not displayed in HomeKit app try this procedure:
Go to ./homebridge/persist.
Remove AccessoryInfo.xxx file which contain Your device data: {"displayName":"Envoy"}.
Next remove IdentifierCashe.xxx file with same name as AccessoryInfo.xxx.
Restart Homebridge and try add it to the Home app again.

**Comment by grzegorz914** [comment]
See this: 
https://github.com/grzegorz914/homebridge-enphase-envoy/issues/92
