### ISSUE TITLE
Is there a way to control the profile from an automation?

### ISSUE THREAD

**Issue by eric-chamberlain-ck** [grzegorz914/homebridge-enphase-envoy#99]
Hello, is there a way to control the charge profile from an automation?

I want full charge mode in the morning, then self-sufficient during peak, as an example.

**Comment by grzegorz914** [comment]
Not now but can be integrated in feature.

**Comment by grzegorz914** [comment]
Can you post some screenshots and profiles names hot this looks in your app because I don't have battery in my system.

**Comment by echamberlain** [comment]
What do you want screenshots of? Enphase app or homebridge logs?

**Comment by grzegorz914** [comment]
Enphase app with profiles

**Comment by echamberlain** [comment]
Sorry for the delay.  Here's what the app screenshots look like:

![IMG_0250](https://github.com/grzegorz914/homebridge-enphase-envoy/assets/117235/850ff0ae-dc25-4340-90e0-af6ced9a0129)
![IMG_0251](https://github.com/grzegorz914/homebridge-enphase-envoy/assets/117235/b37cf4bd-65a3-44e9-8623-a93070e61a29)
![IMG_0252](https://github.com/grzegorz914/homebridge-enphase-envoy/assets/117235/ca26e423-9bb9-48be-b0a0-b7ab08eeb2fc)
![IMG_0253](https://github.com/grzegorz914/homebridge-enphase-envoy/assets/117235/cc104444-9fbd-4080-b366-27f39dcbc4ec)

**Comment by tylerbenson** [comment]
A while ago I created a separate plugin to do this via the cloud api endpoints, but would rather do it via local endpoints using this plugin.

https://github.com/tylerbenson/homebridge-enphase-battery#readme

I'm not great at Javascript, but let me know if I can help.

**Comment by grzegorz914** [comment]
I will start to add this possibility but I will need some one for test because I do not have encharges.

**Comment by grzegorz914** [comment]
Can you post 3 debugs logs, one with Full Bakup enabled , one with Savings and Reserve 30% and one wit Self Consumption  and Reserve 75%.

**Comment by tylerbenson** [comment]
I think the best way to have this work with homebridge is to have a toggle that changes the profile to full backup when enabled and back to one of the other options when disabled.  In my plugin I implemented it as changing the reserve, but I've run into problems where it doesn't seem to work reliably.

**Comment by tylerbenson** [comment]
I ended up refactoring my plugin to switch profiles instead of adjusting the reserve amount.  I think it's working better now.

**Comment by grzegorz914** [comment]
Right now I don't see possibility in local api to control encharge profile, if I found solution then will be added in future release. Technically is possible to read and control this data from Web API but I don want to mix this in current app. I will look into this in future.

**Comment by tylerbenson** [comment]
I ended up switching over to home assistant.  The enphase integration there does allow for profile switching and I believe it is all local. Might be worth looking at their code for comparison.

**Comment by tylerbenson** [comment]
Glad you were able to figure it out!

**Comment by echamberlain** [comment]
Thanks. I'll test it out when I get back from traveling.
